name: Deploy

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy and execute script on EC2 instance
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOSTNAME: ${{ secrets.HOSTNAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        export user="ubuntu"
        
        echo "Debugging Environment Variables"
        echo "Hostname: ${HOSTNAME}"
        echo "Username: ${user}"
        
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        
        # Copy the script to the EC2 instance
        echo "Copying script to EC2 instance..."
        scp -o StrictHostKeyChecking=no -i private_key ./00_ec2/ec2_user_data.sh "${user}@${HOSTNAME}:/home/${user}/ec2_user_data.sh"
        
        # Verify the file was copied correctly
        echo "Verifying script on EC2 instance..."
        ssh -o StrictHostKeyChecking=no -i private_key "${user}@${HOSTNAME}" "ls -l /home/${user}/ec2_user_data.sh"
        
        # SSH into the EC2 instance and run the script with AWS credentials
        echo "Running script on EC2 instance with AWS credentials..."
        ssh -o StrictHostKeyChecking=no -i private_key "${user}@${HOSTNAME}" "
          export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
          /home/${user}/ec2_user_data.sh
        "
